name: Publish to NPM
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4

      - name: ⎔ Get Node Version
        id: node_version
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: ⎔ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.node_version.outputs.NVMRC }}"
          cache: npm

      - name: 📦 Install Dependencies
        run: npm ci

      - name: ⬆️ Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
